### ISSUE TITLE
Render Tags Correctly

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-asset-view#20]
**Describe the bug**
The tags field should render the response as a list. Currently, all the tags get mushed together into one string.

**To Reproduce**
1. Run npm start
2. Click on 'submit'
3. Notice the data in the tags field gets mushed together

**Expected behavior**
The tags should be rendered in a better way. (Maybe a drop-down?)

**Screenshots**
![tags_ecephys_raw](https://user-images.githubusercontent.com/104453205/197254418-62def1e0-2a57-44ad-ae2d-7971d4eec4d2.png)

**Desktop (please complete the following information):**
 - OS: CentOs
 - Browser Chrome/Firefox

**Additional context**

**Comment by dana-rocha** [comment]
Current Tags column in Material UI Table

<img width="939" alt="tags" src="https://user-images.githubusercontent.com/46910672/209274303-67080509-df55-4464-a19d-48b6e23ef249.PNG">

**Comment by dana-rocha** [comment]
Can use [MUI Chip components](https://mui.com/material-ui/react-chip/) to format the tags

**Comment by jtyoung84** [comment]
No longer supported
