### ISSUE TITLE
Tech-debt, put hard-coded endpoints into configs.

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-asset-view#24]
# User story
As a developer, I want well-organized code, so I can maintain the code base.

# Acceptance criteria
- [ ] The url endpoints should be moved to a config file.

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified
6. - [ ] Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by dana-rocha** [comment]
Put proxy server endpoint in .ENV file or JS file
