### ISSUE TITLE
Use a table plugin to render the data asset table

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-asset-view#28]
Right now the data asset table is unstyled.  Find a react table plugin (e.g. `react-table`), use it to render your table and apply one of the standard themes.

**Comment by dana-rocha** [comment]
- Currently exploring Material UI as an alternative to react-table
- Planning to work on styling on top of Material UI after it's been implemented

**Comment by dana-rocha** [comment]
- Implemented table of datasets with Material UI
- Currently working a table that shows both datasets and results
