### ISSUE TITLE
Add Github action to manage tags

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-asset-view#3]
# User story
As a user, I want to easily see which version is most up to date on GitHub, so I can update if necessary.

# Acceptance criteria
- [ ] When a pull request is merged into main, then a tag matching the semantic version will be created.

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified
6. - [ ] Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by dana-rocha** [comment]
Closed by https://github.com/AllenNeuralDynamics/aind-data-asset-view/pull/34
