### ISSUE TITLE
Prettier and ESLint conflicts

### ISSUE THREAD

**Issue by dana-rocha** [AllenNeuralDynamics/aind-data-asset-view#35]
**Describe the bug**
The Prettier formatter and ESLint linter conflict with each other. 

**To Reproduce**
1. Run `npm run format-fix` and `npm run format`
2. Run `npm run lint-fix` and `npm run lint`
3. Changes alternate back and forth between Prettier and ESLint

**Expected behavior**
Prettier and ESLint should agree

**Additional context**

**Comment by jtyoung84** [comment]
It looks like this issue has been resolved
