### ISSUE TITLE
Capsule View

### ISSUE THREAD

**Issue by dana-rocha** [AllenNeuralDynamics/aind-data-asset-view#42]
**Is your feature request related to a problem? Please describe.**
With the current features of the [CodeOcean Capsule API](https://docs.codeocean.com/user-guide/code-ocean-api/capsule-api), one cannot request all the capsule ids to display the metadata for all the capsules. 

**Describe the solution you'd like**
When a user navigates to the Capsule View page, a user can input one capsule id in a field and the metadata for that capsule is displayed.

**Comment by dyf** [comment]
No API for this, closing for now.
