### ISSUE TITLE
Server-side pagination

### ISSUE THREAD

**Issue by dana-rocha** [AllenNeuralDynamics/aind-data-asset-view#47]
# User story
As a user, I want to view all data assets registered in Code Ocean

# Acceptance criteria
- [ ] Can view the next 10 data assets when selecting the next page of the table

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified
6. - [ ] Ticket is prioritized and sized

# Notes
[MUI DataGrid - Server Side pagination](https://mui.com/x/react-data-grid/pagination/#server-side-pagination)

**Comment by jtyoung84** [comment]
Not currently possible
