### ISSUE TITLE
View provenance of result assets

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-asset-view#49]
# User story
As a visitor, I want to understand how results were generated.

# Acceptance criteria
- [ ] See a list of all results assets
- [ ] For each result asset, see what capsule generated it 
    - name
    - version
    - date and time of run
    - link to capsule
    - link to github (if available) <-- go ahead and fake this e.g. (`https://github.com/allenneuraldynamics/<capsule_name>`)
- [ ] For each result asset, see which raw data it was derived from
    - name
    - tags

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified
6. - [ ] Ticket is prioritized and sized

# Notes
- We used to call this the "pipeline run view."
- Only need to go back one "hop" in the provenance chain.

**Comment by dana-rocha** [comment]
- Different page from Data Asset View
- Date and time of run (sometimes called Computations or Runs in CO
- Placeholder link (fake link) is good for now
- First step: can we get this data organized

**Comment by jtyoung84** [comment]
Not currently a milestone
